version: "3.8"
services:
  api:
    build: ./api
    restart: always
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - POSTGRES_DSN=${POSTGRES_DSN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  caddy:
    image: caddy:2.5.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z
volumes:
  db:
    driver: local
