version: "3.8"
services:
  api:
    build: ./api
    restart: always
    ports:
      - ${API_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ROOT_FIRSTNAME=${ROOT_FIRSTNAME}
      - ROOT_LASTNAME=${ROOT_LASTNAME}
      - ROOT_EMAIL=${ROOT_EMAIL}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
    networks:
      - local-keycloak
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - local-keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRES_DSN}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command:
      - start-dev
    networks:
      - local-keycloak
volumes:
  db:
    driver: local
networks:
  local-keycloak:
