version: "3.8"
services:
  api:
    build: ./api
    restart: always
    ports:
      - ${API_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    command: ["start","--auto-build","--http-enabled=true","--hostname-strict=false","--hostname-strict-https=false","--import-realm"]
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KC_DB_URL=${KC_POSTGRES_DSN}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_DB=postgres
    ports:
      - "8080:8080"
    volumes:
      - ./realms/realm.json:/opt/keycloak/data/import/realm.json:z
volumes:
  db:
    driver: local

