version: "3.8"
services:
  api:
    build: ./api
    restart: always
    ports:
      - ${API_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ROOT_FIRSTNAME=${ROOT_FIRSTNAME}
      - ROOT_LASTNAME=${ROOT_LASTNAME}
      - ROOT_EMAIL=${ROOT_EMAIL}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./realms/realm.json:/opt/keycloak/data/import/realm.json:ro
volumes:
  db:
    driver: local

