version: "3.8"
services:
  caddy:
    image: caddy:2.5.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - AUTH_SUBDOMAIN=${AUTH_SUBDOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z
  api:
    build:
      context: .
    restart: always
    expose:
      - "4000"
    environment:
      - SERVER_PORT=4000
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_DSN=${POSTGRES_DSN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_DOMAIN=${APP_DOMAIN}
      - AUTH_SUBDOMAIN=${AUTH_SUBDOMAIN}
      - KC_REALM=${KC_REALM}
      - KC_CLIENT=${KC_CLIENT}
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    command: ["start", "--auto-build", "--import-realm", "--proxy=edge"]
    restart: always
    expose:
      - "8080"
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KC_DB_URL=${KC_POSTGRES_DSN}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_DB=postgres
      - KC_HOSTNAME=${AUTH_SUBDOMAIN}.${APP_DOMAIN}
      - APP_DOMAIN=${APP_DOMAIN}
      - KC_REALM=${KC_REALM}
      - KC_CLIENT=${KC_CLIENT}
    volumes:
      - ./realms/realm.json:/opt/keycloak/data/import/realm.json:z
volumes:
  db:
    driver: local
