version: "3.8"
services:
  api:
    build: ./api
    restart: always
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - POSTGRES_DSN=${POSTGRES_DSN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ROOT_FIRSTNAME=${ROOT_FIRSTNAME}
      - ROOT_LASTNAME=${ROOT_LASTNAME}
      - ROOT_EMAIL=${ROOT_EMAIL}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  caddy:
    image: caddy:2.5.1-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from :80 --to api:8080
    ports:
      - "80:80"
      - "443:443"
    links:
      - api
volumes:
  db:
    driver: local
