package com.example.servermaintenance.course;

import com.example.servermaintenance.account.Account;
import com.example.servermaintenance.interpreter.Interpreter;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;

import javax.transaction.Transactional;
import java.util.Comparator;
import java.util.List;

@Service
@AllArgsConstructor
public class CourseStudentService {
    private final CourseStudentRepository courseStudentRepository;
    private final CourseStudentPartRepository courseStudentPartRepository;

    @Transactional
    public CourseStudent generate(Course course, Account account, long id) {
        // TODO: get from repo with order
        var schema = course.getSchemaParts().stream().sorted(Comparator.comparingInt(SchemaPart::getOrder)).toList();
        var courseStudent = new CourseStudent(account, course, id);
        for (SchemaPart part : schema) {
            var courseStudentPart = new CourseStudentPart(courseStudent, part);
            if (!part.isAutogenerated()) {
                courseStudentPart.setData("");
            } else {
                courseStudentPart.setData(Interpreter.eval(part.getGenerationStatement(), id));
            }
            courseStudent.addCourseStudentPart(courseStudentPartRepository.save(courseStudentPart));
        }
        return courseStudentRepository.save(courseStudent);
    }

    public CourseStudent getCourseStudent(Course course, Account account) {
        return courseStudentRepository.findFirstByCourseAndAccount(course, account);
    }

    public List<CourseStudentPart> getCourseStudentParts(Course course, Account account) {
        return courseStudentRepository.findFirstByCourseAndAccount(course, account)
                .getCourseStudentParts()
                .stream()
                .sorted(Comparator.comparingInt(a -> a.getSchemaPart().getOrder()))
                .toList();
    }
}
