package com.example.servermaintenance.courseschema;

import com.example.servermaintenance.course.Course;
import lombok.*;

import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

@Entity
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Table(name = "course_schema_part")
public class CourseSchemaPart implements Serializable{
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "name")
    private String name;

    @Column(name = "validator")
    private boolean validator;

    @Column(name = "validator_regex")
    private String validatorRegex;

    @Column(name = "validator_message")
    private String validatorMessage;

    @Column(name = "locked")
    private boolean locked;

    @Column(name = "autogenerated")
    private boolean autogenerated;

    @Column(name = "generation_statement")
    private String generationStatement;

    @Column(name = "control_width")
    private int controlWidth;

    @Column(name = "orderr")
    private int order;

    @Column(name = "required")
    private boolean required;

    @ManyToOne
    @JoinColumn(name = "course_id")
    private Course course;

    @ManyToOne
    @JoinColumn(name = "data_type")
    private DataType dataType;

    @OneToMany(mappedBy = "courseSchemaPart")
    private List<CourseDataPart> courseDataParts;

}
